### ISSUE TITLE
not all language pairs show up for specific areas

### ISSUE THREAD

**Issue by e-schott** [e-schott/youngest-bilingual-canadians-2022#10]
e.g. kitchener, oshawa, peterborough don't show in table

**Comment by e-schott** [comment]
also, gatineau should match to ottawa-gatineau partie du quebec

**Comment by e-schott** [comment]
actually I think this affected all hyphenated areas. KElowna-Abbortsford, REgina-Saskatoon,...

**Comment by surchs** [comment]
I think this is addressed with 2bdeccc. The problem was that the compound region names in the [`assets/language_pairs.csv` file](https://github.com/e-schott/youngest-bilingual-canadians-2022/blob/main/assets/language_pairs.csv) are using the emdash but the region names use a normal dash. I have fixed this in the app. But I am not sure whether Ottawa-Gatineau is working correctly. 

@e-schott can you check for Ottawa-Gatineau and see if the values are OK? Otherwise we might just need a hard-coded fix for this one region
